### ISSUE TITLE
TLS vocalize restore

### ISSUE THREAD

**Issue by lunatixxx** [Target5150/MoYu_Server_Stupid_Plugins#7]
There is a conflict between your plugin and anti spam vocalize who works with sceneprocessor. 
Vocalize line limits in a dozen of seconds:
without plugin -> 4 normally
with plugin -> 2

**Comment by jensewe** [comment]
Not sure if there's much can be done on this one. Could you upload a copy of the anti-spam plugin that you're using?

**Comment by lunatixxx** [comment]
https://forums.alliedmods.net/showthread.php?t=241588

**Comment by jensewe** [comment]
Theoretically there shouldn't be conflict between these two, as `initiator` defaults to -1 in `PerformScene`, thus being ignored in anti-flood plugin.
Maybe I should test it on my end for sure.

**Comment by jensewe** [comment]
Sorry for a long time investigation ~~im not lazy~~

For now I think I couldn't offer a solid solution, while there're some tricks to avoid this issue.

This issue is somehow related to how sourcemod forward works. In short, it can be tackled if you try loading the **Vocalize Restore** plugin after the **Anti-Flood** plugin.

There're another 2 ways that I could think of:

1. Ask the sceneprocessor author to add a forward of **OnVocalizeCommand_Post**, or sourcemod developers to add methods to **post-hook command**, and move my stuff in there.
2. Just do `Plugin_Stop` in **OnVocalizeCommand** in my plugin, so the manual performed scenes will somehow be considered as "world" or non-self-initiated scenes.

Neither of them is good in my opinion, but the second one is viable if people always use that Anti-Flood plugin, since I'm not sure how other similar plugins work (especially those not relying on **sceneprocessor**), and whether this change will break them.

I might commit a change in the second way later.

**Comment by jensewe** [comment]
Should be all good with the latest version, as it won't produce another vocalization anymore.

**Comment by lunatixxx** [comment]
I tested now and noticed that the vocalizer use english lines even with other langages. I know it's a problem since last stand, nothing we can do?
